import NavBar from "components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
// import { cards } from "../../utils/content";
import Article from "../article";
import Image from "next/image";
import { attributes, react as HomeContent } from '../../content/home.md';

export default function Home() {
  let {posts} = attributes;

  const router = useRouter();
  const { id } = router.query;
  const c = posts.find((posted : any) => posted.id.toString() === id);
  // console.log(c);

  const co = { id: 0, articleTitle: "d", content: "j", logo: "/img", author: "c" }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://identity.netlify.com/v1/netlify-identity-widget.js"
          async
        ></script>
      </Head>
      <div >
        <NavBar />
        <Article content={c} />
      </div>
    </div>
  );
}
